### ISSUE TITLE
Validate multiple schemas

### ISSUE THREAD

**Issue by zaggino** [petrbela/grunt-z-schema#1]
Hi,
nice work. I'd add this to some of my projects, but it need a feature to specify not just only one schema, but multiple files or even better, a directory where all `json` files would be validated.

**Comment by petrbela** [comment]
Good point, I'll add support for multiple schemas. The directory scan can be achieved with the file regex in grunt, I'll add an example to the docs.

**Comment by petrbela** [comment]
Closed by f80e164ecbb726fdcf31471e135209322e13f5f8
